# Generated by Django 3.1.7 on 2021-04-19 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('fecha_realizada', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destino', to=settings.AUTH_USER_MODEL)),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='origen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
